"""alter user with role field

Revision ID: 7d83c947715b
Revises: e85343e0c5e3
Create Date: 2019-10-20 23:21:09.047812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d83c947715b'
down_revision = 'e85343e0c5e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.Enum('admin', 'user', name='roleschoices'), server_default='user', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
