"""alter user with qoute field

Revision ID: d800277ba954
Revises: 7d83c947715b
Create Date: 2019-11-09 20:56:12.448851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd800277ba954'
down_revision = '7d83c947715b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('quote', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'quote')
    # ### end Alembic commands ###
